### PR TITLE
Fix callback URL not mounted right when router has nested paths.

### PR DESCRIPTION
**Pull request by williamweckl**
Fixes https://github.com/ueberauth/ueberauth/issues/165

### CODE REVIEW

**Comment by williamweckl** [comment]
Now I see that was already a PR to fix the issue... What's the impediment to merge https://github.com/ueberauth/ueberauth/pull/147 ?

**Comment by yordis** [comment]
Do you mind doing the following:

- bump the version in the mix.exs following SemVer.
- add an entry to CHANGELOG.md

More details at: https://github.com/ueberauth/ueberauth/blob/master/CONTRIBUTING.md

**Comment by yordis** [comment]
This is related to https://github.com/ueberauth/ueberauth/pull/147 it seems

**Comment by williamweckl** [comment]
Yes, it is related... But I think that @[starkeepers](https://github.com/starkeepers) abandoned it, there are also no tests on the PR.

I'll add the changelog entry and bump the version.

**Comment by williamweckl** [comment]
Done!

**Pull request merged**
