### PR TITLE
fix: callback_url/1 uses conn.port by default

### PR DESCRIPTION
**Pull request by gf3**
Without any additional configuration the `conn` port was not being included in the built callback URL and instead the default port of `80` was used.

This PR corrects that omission and adds a test to prevent regressions.

### CODE REVIEW

**Comment by gf3** [comment]
Looking into the commit logs, it seems that this functionality was intentionally removed: https://github.com/ueberauth/ueberauth/commit/b1d0872aafea0bd31ff4b1678eb93a4ea0078bb6

I would consider this a regression, as it breaks in many current browsers which do not include a `host` header and instead include an `authority` header. Here's an example request from a current version of Chrome:

```sh
curl 'https://sys.freshline.dev:5555/auth/google' \
  -H 'authority: sys.freshline.dev:5555' \
  -H 'accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7' \
  -H 'accept-language: en-US,en;q=0.9' \
  -H 'cache-control: max-age=0' \
  -H 'cookie: _internal_web_key=...' \
  -H 'referer: https://sys.freshline.dev:5555/auth/google' \
  -H 'sec-ch-ua: "Chromium";v="116", "Not)A;Brand";v="24", "Google Chrome";v="116"' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'sec-ch-ua-platform: "Linux"' \
  -H 'sec-fetch-dest: document' \
  -H 'sec-fetch-mode: navigate' \
  -H 'sec-fetch-site: same-origin' \
  -H 'sec-fetch-user: ?1' \
  -H 'upgrade-insecure-requests: 1' \
  -H 'user-agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36' \
  --compressed
```

An alternative approach would be to update `get_host_header\1` to also attempt to check the `authority` header.

cc: @wkirschbaum

**Comment by wkirschbaum** [comment]
Just be careful to use conn.port, as cowboy seems to handle this in an opinionated manner and will be incompatible with bandit.  From my memory  there is a problem identifying if the port is actually set or should just be a default port which then makes the wrong call and breaks redirects usng bandit.

I can have a more detailed look a bit later.

**Comment by wkirschbaum** [comment]
@gf3 I think it will be more correct if cowboy/bandit set the conn.host value correctly, instead of ueberauth caring about how it gets retrieved, no? The get_host_header function is really just there to handle x-forwarded-host, which I believe for security reasons won't make sense to the web server to consider.

**Comment by yordis** [comment]
I am frustrated with myself. I do not want to be causing "regressions," but so tricky when different parties understand a loose RFC 😞 

Who is right?! 🤷🏻 😞  Please share your perspective. I am not an expert on the topic. As @mtrudel said, "Ultimately, this comes down to what we want %Plug.Conn{port: ...} to mean."

**Comment by gf3** [comment]
I don't feel too strongly. Since this is a high-level library I think the best path forward would be to operate in a way that users expect (instead of strictly adhereing to specifications). And in this case, in a Phoenix/Plug application, by default ueberauth should generate a callback URL that matches the **public** application URL. So the more I think on it, the more I believe that your solution of manually parsing the request headers is the correct one @wkirschbaum.

**Comment by wkirschbaum** [comment]
@yordis sorry you feel frustrated. I lean towards how bandit works, but we have to consider cowboy and the fact that it might not be possible to make any changes there within reasonable time. It seems that neither cowboy or bandit handles the authority header as described here, so thinking it might cause more issues elsewhere? Is it worth asking @mtrudel? 

@gf3 unfortunately defaulting to conn.port for bandit behind a firewall will mean that the redirect will use the underlying port, not the default scheme's port, which won't be part of the host header.

**Comment by wkirschbaum** [comment]
> I don't feel too strongly. Since this is a high-level library I think the best path forward would be to operate in a way that users expect (instead of strictly adhereing to specifications). And in this case, in a Phoenix/Plug application, by default ueberauth should generate a callback URL that matches the **public** application URL. So the more I think on it, the more I believe that your solution of manually parsing the request headers is the correct one @wkirschbaum.

I think we can add it, if there is no security issues. Technically this must only be considered for http2 it seems.

**Comment by yordis** [comment]
I will wait a bit for @mtrudel, hopefully, just to have a combined argument.

In the worst case, we can always opt-in to DI and inject the behavior you wish to have 🤷🏻

**Comment by mtrudel** [comment]
> Technically this must only be considered for http2 it seems.

This is simultaneously completely true, bogus as hell, and exactly the problem with all of this.

The point of Plug is to abstract HTTP.  The above is about as perfect of a sample of abstraction as you're going to find. Uber auto shouldn't have to care one wit that a given connection is h2 or not; if it does, the abstraction has failed us.

This is cut from very similar cloth to https://github.com/phoenixframework/phoenix/pull/5553, and I think the right solution here would be to codify the responsibilities at play in terms of url construction, especially in terms of what 'kind' of url you're taking about (as I've talked about previously). 

I'm happy to carry as much of this as necessary; it's a huge bugaboo of mine and is a big part of how we go from One to More Than One http stacks in the language.

**Comment by gf3** [comment]
Thank you for the context, @mtrudel, that's very helpful. 

Given the use-case of this library perhaps we should avoid constructing URLs with Plug.Conn altogether and defer to [`c:Endpoint.url/0`](https://hexdocs.pm/phoenix/Phoenix.Endpoint.html#c:url/0) since this value is often [configured explicitly](https://github.com/phoenixframework/phoenix/blob/4506bc0c511e1bf7b8e42e02dca39e5bb7e2841b/installer/templates/phx_single/config/runtime.exs#L36-L49) and not inferred from request details?

**Comment by mtrudel** [comment]
>

**Comment by mtrudel** [comment]
> Given the use-case of this library perhaps we should avoid constructing URLs with Plug.Conn altogether and defer to c:Endpoint.url/0 since this value is often configured explicitly and not inferred from request details?

Yeah I think that's directionally correct insofar as uberauth should be appealing to some other authority. Whether that's Phoenix or Plug is an open question in my mind; I can see compelling reasons for both (thoughts welcome)

**Comment by wkirschbaum** [comment]
> Thank you for the context, @mtrudel, that's very helpful.
> 
> Given the use-case of this library perhaps we should avoid constructing URLs with Plug.Conn altogether and defer to [`c:Endpoint.url/0`](https://hexdocs.pm/phoenix/Phoenix.Endpoint.html#c:url/0) since this value is often [configured explicitly](https://github.com/phoenixframework/phoenix/blob/4506bc0c511e1bf7b8e42e02dca39e5bb7e2841b/installer/templates/phx_single/config/runtime.exs#L36-L49) and not inferred from request details?

This will break for applications hosted under multiple domains, so some request inspection will be necessary to get the request domain. 

@mtrudel thinking about this more I think bandit is doing something strange with getting the host and port, which is going back to the original issue I logged ( this time hopefully better worded ): 

with this request: 

```bash
curl -H "Host: foo.co.za:222" http://localhost:4000
```
The host will be extracted from the Host header, and the port from the host header. This will then produce foo.co.za, 222

```bash
curl -H  http://localhost:4000
```
The host will be extracted from the underlying transport, and the port from the underlying transport. This will then produce localhost, 4000

Both the above cases work the same for cowboy and bandit, but also in both these cases the pair for host and port gets respected.  But in the following case something different happens only in Bandit:

```bash
curl -H "Host: foo.co.za" http://localhost:4000
```
The host will be extracted from the Host header, but the port from the underlying transport. This will then produces foo.co.za, 4000. Here there is combination of the host, port pairs... so this causes the mismatch and the issues with bandit.  I don't believe there is a scenario where it is correct to mix and match what comes through as a header and what the underlying transport used. 

When there is no port with either a host header/authority header, it must not declare there is no port, because this is not accurate, the port will be the default port for the specified scheme. 

The original argument here: "This is strictly more correct than Cowboy's blind assumption of port 80, and not something I'll entertain changing just for the sake of compatibility. Cowboy is wrong here, not us." makes sense if we assume it is blindly assuming, but in fact, it is saying that if no port is given, it must be port 80 for http since there is no other valid source of information to extract this from, so we have to look at the default. 

I don't think Cowboy is blindly assuming and think Bandit should default to the appropriate port and not try to extract the port from an different source. If the host header is set, that should be the only source, if not, the underlying transport can be used.

**Comment by wkirschbaum** [comment]
I think this explains it, but also

https://www.rfc-editor.org/rfc/rfc9110#section-4.2.1

```
The origin server for an "http" URI is identified by the [authority](https://www.rfc-editor.org/rfc/rfc9110#uri.references) component, which includes a host identifier ([[URI](https://www.rfc-editor.org/rfc/rfc9110#URI)], [Section 3.2.2](https://www.rfc-editor.org/rfc/rfc3986#section-3.2.2)) and optional port number ([[URI](https://www.rfc-editor.org/rfc/rfc9110#URI)], [Section 3.2.3](https://www.rfc-editor.org/rfc/rfc3986#section-3.2.3)). If the port subcomponent is empty or not given, TCP port 80 (the reserved port for WWW services) is the default.
```

and 

https://www.rfc-editor.org/rfc/rfc9110#section-4.2.2

```
The origin server for an "https" URI is identified by the [authority](https://www.rfc-editor.org/rfc/rfc9110#uri.references) component, which includes a host identifier ([[URI](https://www.rfc-editor.org/rfc/rfc9110#URI)], [Section 3.2.2](https://www.rfc-editor.org/rfc/rfc3986#section-3.2.2)) and optional port number ([[URI](https://www.rfc-editor.org/rfc/rfc9110#URI)], [Section 3.2.3](https://www.rfc-editor.org/rfc/rfc3986#section-3.2.3)). If the port subcomponent is empty or not given, TCP port 443 (the reserved port for HTTP over TLS) is the default.
```

also: https://www.rfc-editor.org/rfc/rfc9110#section-4.3.1

```
The "origin" for a given URI is the triple of scheme, host, and port after normalizing the scheme and host to lowercase and normalizing the port to remove any leading zeros. If port is elided from the URI, the default port for that scheme is used. For example, the URI
```

From what I understand, they have to be handled as a triple and should not be mixed.

**Comment by wkirschbaum** [comment]
Given all of that. If Bandit has the default port set, then this proposed change will make 100% sense.

**Comment by yordis** [comment]
Hey folks, any updates over here?

**Comment by gf3** [comment]
> Hey folks, any updates over here?

@yordis i don't think this PR should be merged until there is consensus in the underlying libraries about how ports should be surfaced.

**Comment by mtrudel** [comment]
@wkirschbaum 

> I think this explains it
> 
> [a number of RFC9110§4.2.x references]

Thanks for the clear description! I've gone back and revisited the original reasoning behind https://github.com/mtrudel/bandit/issues/106 and I now see a path forward based on the specs. I'll be updating Bandit to reflect this shortly, at which point I *think* this PR can go ahead as is. 

Thanks for the thoughtful note!

**Comment by wkirschbaum** [comment]
Fantastic! I will test as much as possible as we have Bandit and Cowbow in production with Ueberauth.

**Comment by mtrudel** [comment]
If anyone wants to review the Bandit PR mentioned above it's at https://github.com/mtrudel/bandit/pull/228

**Comment by wkirschbaum** [comment]
@gf3 If the bandit change gets merged in, we will need to the following match back ( one I removed ): 

```elixir
  defp normalize_port("https", 80), do: 443
  ```

This proposed change does not work with a common load balancer setup without this match, because the default port will be 80, not 443 ( assuming http is used behind the load balancer), even if proto is "https" as port will not be nil but 80 as the default is being set now. If Bandit sets it to 80, not the underlying port, then we can safely assume the port will be 80 if there is a host header without a port. 
 
I will test a bit more on my side.

**Comment by wkirschbaum** [comment]
It still feels like we are missing something in Plug or Endpoint where we can easily distinguish between underlying transport parameters and end-user transport parameters for navigation.

**Comment by mtrudel** [comment]
> It still feels like we are missing something in Plug or Endpoint where we can easily distinguish between underlying transport parameters and end-user transport parameters for navigation.

The work I'm undertaking shortly as described at the bottom of https://github.com/phoenixframework/phoenix/pull/5553 will mitigate this somewhat

**Comment by wkirschbaum** [comment]
I tested with 

```
      {:bandit, github: "mtrudel/bandit", override: true},
      {:ueberauth,
       github: "floatpays/ueberauth", branch: "callback-url-fix", override: true},
```

and with cowboy 

```
{:ueberauth,
       github: "floatpays/ueberauth", branch: "callback-url-fix", override: true}
```

which is the proposed change, but also matching on port 80 as ueberauth used to work before I broke it for non default https ports. This works for local development and a https -> http proxy setup. 

@gf3 Do you mind testing my branch to see if it fixes your issue? There is one 

I am confident this is the change we should make until there is a more generic plug solution. We might want to wait for bandit 1.0 to not break existing production usage. 

my change only update 
```diff
@@ -253,7 +256,7 @@ defmodule Ueberauth.Strategy.Helpers do
     end
   end
 
-  defp normalize_port(scheme, nil), do: URI.default_port(scheme)
+  defp normalize_port(scheme, "80"), do: URI.default_port(scheme)
   defp normalize_port(_, port), do: String.to_integer(port)
 
   defp encode_query([]), do: nil
```

**Comment by wkirschbaum** [comment]
I forgot to link the branch ( the one working in all the scenarious tested above ): https://github.com/floatpays/ueberauth/tree/callback-url-fix

**Comment by gf3** [comment]
@wkirschbaum thank you, i will try to get to this at some point soon however i will be away for jury duty.

**Comment by mtrudel** [comment]
Dependent work is merged upstream. See https://github.com/phoenixframework/phoenix/pull/5620

**Comment by markquezada** [comment]
Hi all, got bit by this today. This branch does fix it for us. Any updates?

**Comment by markquezada** [comment]
@gf3 @wkirschbaum hi guys, any chance we could get this merged in? Is there a problem with this approach? Happy to jump in and contribute some code if you can point me in the right direction.

**Comment by gf3** [comment]
thanks for the reminder! i've rebased master onto my feature branch and re-added @wkirschbaum's port normalization fix. it should be good to go now :crossed_fingers:

**Review by yordis — APPROVED** [review]

**Comment by wkirschbaum** [comment]
@yordis I will have a look and test as soon as possible.

**Review by wkirschbaum — APPROVED** [review]
I am happy with these changes and tested it on 2 different environments.

**Review by wkirschbaum — APPROVED** [review]

**Comment by markquezada** [comment]
Thanks guys 🙌

**Pull request merged**
