### PR TITLE
Next Release

### PR DESCRIPTION
**Pull request by yordis**

### CODE REVIEW

**Comment by yordis** [comment]
@Hanspagh @doomspork let me know, we need to follow up in adding support for the state params per client.

**Comment by doomspork** [comment]
@yordis what needs to happen with the strategies? Let's get those PRs ready to go.

**Comment by yordis** [comment]
@doomspork it depends on the strategy code, for the most part:

1. Verify if the strategy supports CQRS
2. Read the token from the privates
3. Inject the token into the `state` query param
4. Repeat

**Comment by yordis** [comment]
@doomspork anything you need from my side?

**Comment by benwilson512** [comment]
Any working examples of the changes required in a client?

**Comment by yordis** [comment]
@benwilson512 I can work on one, the problem is that each client does its own thing and we lack shared tooling, so it all depends on the client code.

## Steps to Implements

1. Figure out if your OAuth2 Provider implements CSRF Attack (state params)
  1.1. IF DOES implement CSRF Attack, add `use Ueberauth.Strategy, ignores_csrf_attack: true` to your strategy
    1.1.1. Read the `state` param from the Conn `state = conn.private[:ueberauth_state_param]`
    1.1.2. Add the state param to the query param of your request following the client specification about `state` param
      1.1.2.1 In case the spec uses `state` use `Ueberauth.Strategy.Helpers. with_state_param/2`
      1.1.2.2 DONE
  1.2 IF DOES NOT implement CSRF Attack
      1.2.1. Disabled the flag, add `use Ueberauth.Strategy, ignores_csrf_attack: false` to your strategy
      1.2.2. DONE

**Comment by xinz** [comment]
Hello,

I find the previous comment may exist conflicts, could you please double check? cc @yordis 
 
### With CSRF Attack Support

> IF DOES implement CSRF Attack, add use Ueberauth.Strategy, ignores_csrf_attack: true to your strategy

In this case, it should be `ignores_csrf_attack: false`, as the current code base default setting.

### With out CSRF Attack Support

> Disabled the flag, add use Ueberauth.Strategy, ignores_csrf_attack: false to your strategy

In this case, it should be `ignores_csrf_attack: true`.

**Comment by doomspork** [comment]
@yordis I haven't had a chance to work on updating anything related to this. We need to create issues for everything outstanding and work through it.

**Comment by yordis** [comment]
@doomspork I can take full ownership of everything, I don't think you need to worry about it, but I need some code reviews, I don't want to merge it without the 1+

**Comment by yordis** [comment]
Any updates @ueberauth/developers or should I merge it and continue with the work required in the clients?

**Comment by xinz** [comment]
Hi @yordis, I have one more comment need you review, I will post it asap.

**Review by doomspork — APPROVED** [review]
This looks good. I am interested in @xinz's comment :thinking:

**Comment by xinz** [comment]
Hi, here are my find, please review https://github.com/ueberauth/ueberauth/pull/139

**Review by Hanspagh — APPROVED** [review]

**Comment by doomspork** [comment]
@yordis with #139 merged I think we're good to cut a new release 🎉

**Comment by jmhossler** [comment]
Is there a good way to test with the new CSRF token? I'm trying to update one of the plugin libraries, but it seems like we don't really have any control or visibility of the generated token which makes it very difficult to make any sort of assertion or validation. This project specifically relies on matching the request based on params to get the connection -- which I can't do unless I know or can set the ueberauth state param beforehand.

**Pull request merged**
