### PR TITLE
Allow config of redirect_uri

### PR DESCRIPTION
**Pull request by nicooga**
Solves problems described at https://github.com/ueberauth/ueberauth/issues/18.

### CODE REVIEW

**Comment by minibikini** [comment]
Please, merge!

**Comment by doomspork** [comment]
The PR is not in a merge-able state, it needs to be rebased.

**Comment by OvermindDL1** [comment]
@doomspork What was wrong with it 1.5 months ago so that could be resolved simultaneously?

**Comment by doomspork** [comment]
@OvermindDL1 sorry none of us are paid to work on Ueberauth, we've all been busy with work.

**Comment by OvermindDL1** [comment]
@doomspork Understandable yep, just curious if there was something wrong with the PR so it can be fixed simultaneously with updating to save time for all?

**Comment by OvermindDL1** [comment]
Speaking of, ping @nicooga

**Comment by doomspork** [comment]
@OvermindDL1 / @nicooga — once this is rebased it should be good to merge unless @hassox has any additional thoughts.

**Comment by nicooga** [comment]
Here! Rebased. There were no non-trivial conflicts and the tests pass.

**Comment by doomspork** [comment]
Thank you @nicooga 👍

**Comment by doomspork** [comment]
This has been released 🎉

**Pull request merged**
