### PR TITLE
Versioning to 0.6.1

### PR DESCRIPTION
**Pull request by yordis**

### CODE REVIEW

**Comment by doomspork** [comment]
https://github.com/ueberauth/ueberauth/commit/57c6b10837a25d69a57bf9971ae0df767ee39e10

Can you rebase to update the changelog? I went ahead and released before I got caught up in other things.

**Comment by doomspork** [comment]
In the future we should ask the PR creator to update the changelog so that is not something we need to keep up with.

**Comment by yordis** [comment]
Words! I know how to fix this, I will add some templates today when I get home

**Comment by doomspork** [comment]
@yordis I don't believe we need this PR any longer, correct?

**Comment by yordis** [comment]
@doomspork yeah remember you asked me to create a release for it :D

**Comment by doomspork** [comment]
@yordis I know but there appears to be nothing in this PR now, right? @evadne added the Changelog entry.

**Comment by yordis** [comment]
@doomspork right, because the release happened already, but we didn't do a `GitHub release` and we didn't update the changelog.

This is not for a Hex release though.

**Comment by doomspork** [comment]
Okay. I pushed 0.6.1 to Hex the other day so I created a tag in GH (I think that's what I meant when I asked you to make a release). We need to prep 0.6.2 for the recent changes @evadne added unless we decide that warrants a 0.7.0.

**Pull request closed without merging**
