### PR TITLE
Add CONTRIBUTING

### PR DESCRIPTION
**Pull request by maxbeizer**
Adds a CONTRIBUTING file to aid people who want to contribute. 

This is just a basic, first pass--suggestions and additions welcome.

### CODE REVIEW

**Comment by doomspork** [comment]
Does this need to be a separate file or can this live in the README?

**Comment by maxbeizer** [comment]
@doomspork Adding this file is a GitHub convention that pops up a link when opening an issue/PR. See [this blog post from GH](https://github.com/blog/1184-contributing-guidelines) for more info.

**Comment by doomspork** [comment]
I'm just wondering about the usefulness.  Speaking for myself, I typically consult the README, fork, and open a PR.  Elixir has a pretty extensive contributing file but it's pretty clear that most people don't familiarize themselves with it.

**Comment by hassox** [comment]
I'm happy to add this. It is supported by GH so we might as well be explicit in our guidlines.

**Comment by scrogson** [comment]
:+1:

**Comment by scrogson** [comment]
:heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:

**Pull request merged**
