### PR TITLE
README tweaks

### PR DESCRIPTION
**Pull request by maxbeizer**
Some simple copy editing of the README.

Happy to squash if you approve of all changes. :beers:

### CODE REVIEW

**Comment by doomspork** [comment]
Please squash.

We've been discussing some changes that may impact this documentation so I'll defer to @scrogson / @hassox for the merge.

**Comment by hassox** [comment]
This is great :) Thanks so much for the effort. Having said that the README is going to change significantly, but I think we can get this in and rebase on it before we update to make sure we get these changes. 

Please squash and we'll get them in.

**Comment by maxbeizer** [comment]
Fixed up. Thanks!

**Comment by scrogson** [comment]
Thanks @maxbeizer!!

**Comment by scrogson** [comment]
:heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:

**Pull request merged**
